<template>
    <section class="faq bg-white py-6 space-y-6">
        <h1 class="text-center font-extrabold text-3xl rounded-md text-black mt-4">Faq</h1>
        <h2 class="text-center text-4xl tracking-normal font-semibold sm:text-4xl md:text"> Get answers to common questions</h2> <br>
        <div class="container mx-auto lg:flex">
            <!-- first row -->
        <div class="bg-white space-y-6 p-6">
            <div class="relative w-full overflow-hidden">
                <input type="checkbox" class="peer absolute top-0 inset-x-0 w-full h-12 opacity-0 z-10 cursor-pointer">
                
                <div class="bg-white border h-12 w-full pl-5 flex items-center">
    
                    <h1 class="text-lg font-semibold text-green">
                        What is a Static Website?
                    </h1>
                </div>
                <div class="absolute top-3 right-3 text-black transition-transform duration-500 rotate-0 peer-checked:rotate-90">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 5l7 7-7 7" />
                      </svg>
                </div>
    
                <div class="bg-white overflow-hidden transition-all duration-500 max-h-0 peer-checked:max-h-full">
                    <div class="p-4">
                        <p>
                            A static website consists only of static webpages. A static web page (sometimes called a flat page or a stationary page) is a web page that is delivered to the user's web browser exactly as stored, in contrast to dynamic web pages which are generated by a web application.
                        </p>
                    </div>
                </div>
            </div>
            <div class="relative w-full overflow-hidden">
                <input type="checkbox" class="peer absolute top-0 inset-x-0 w-full h-12 opacity-0 z-10 cursor-pointer">
                
                <div class="bg-white border h-12 w-full pl-5 flex items-center">
    
                    <h1 class="text-lg font-semibold text-green">
                        What are examples of Static Websites
                    </h1>
                </div>
                <div class="absolute top-3 right-3 text-black transition-transform duration-500 rotate-0 peer-checked:rotate-90">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 5l7 7-7 7" />
                      </svg>
                </div>
    
                <div class="bg-white overflow-hidden transition-all duration-500 max-h-0 peer-checked:max-h-full">
                    <div class="p-4">
                        <p>
                            Usually, static websites are a great beginning for more complicated project. Local businesses could host their menus, agencies could post service descriptions, freelancers could publish portfolios and resumes. There's also place for media like image galleries, videos and even image boards or web apps, if done correctly.
                        </p>
                    </div>
                </div>
            </div>
    
            <div class="relative w-full overflow-hidden">
                <input type="checkbox" class="peer absolute top-0 inset-x-0 w-full h-12 opacity-0 z-10 cursor-pointer">
                
                <div class="bg-white border h-12 w-full pl-5 flex items-center">
    
                    <h1 class="text-lg font-semibold text-green">
                        Do you provide any support?
                    </h1>
                </div>
                <div class="absolute top-3 right-3 text-black transition-transform duration-500 rotate-0 peer-checked:rotate-90">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 5l7 7-7 7" />
                      </svg>
                </div>
    
                <div class="bg-white overflow-hidden transition-all duration-500 max-h-0 peer-checked:max-h-full">
                    <div class="p-4">
                        <p>
                            Yes! Customer support is available!
                        </p>
                    </div>
                </div>
            </div>
        </div>

        
        <!-- second row -->

        
        <div class="bg-grey space-y-6 p-6">
            <div class="relative w-full overflow-hidden ">
                <input type="checkbox" class="peer absolute top-0 inset-x-0 w-full h-12 opacity-0 z-10 cursor-pointer">
                
                <div class="h-12 border w-full pl-5 flex items-center">
    
                    <h1 class="text-lg font-semibold text-green">
                        Do you backup the data?
                    </h1>
                </div>
                <div class="absolute top-3 right-3 text-black transition-transform duration-500 rotate-0 peer-checked:rotate-90">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 5l7 7-7 7" />
                      </svg>
                </div>
    
                <div class="overflow-hidden transition-all duration-500 max-h-0 peer-checked:max-h-full">
                    <div class="p-4">
                        <p>
                            A static website consists only of static webpages. A static web page (sometimes called a flat page or a stationary page) is a web page that is delivered to the user's web browser exactly as stored, in contrast to dynamic web pages which are generated by a web application.
                        </p>
                    </div>
                </div>
            </div>
            <div class="relative w-full overflow-hidden">
                <input type="checkbox" class="peer absolute top-0 inset-x-0 w-full h-12 opacity-0 z-10 cursor-pointer">
                
                <div class="h-12 border w-full pl-5 flex items-center">
    
                    <h1 class="text-lg font-semibold text-green">
                        What is a Static Website?
                    </h1>
                </div>
                <div class="absolute top-3 right-3 text-black transition-transform duration-500 rotate-0 peer-checked:rotate-90">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 5l7 7-7 7" />
                      </svg>
                </div>
    
                <div class="overflow-hidden transition-all duration-500 max-h-0 peer-checked:max-h-full">
                    <div class="p-4">
                        <p>
                            A static website consists only of static webpages. A static web page (sometimes called a flat page or a stationary page) is a web page that is delivered to the user's web browser exactly as stored, in contrast to dynamic web pages which are generated by a web application.
                        </p>
                    </div>
                </div>
            </div>
    
            <div class="relative w-full overflow-hidden">
                <input type="checkbox" class="peer absolute top-0 inset-x-0 w-full h-12 opacity-0 z-10 cursor-pointer">
                
                <div class="h-12 border w-full pl-5 flex items-center">
    
                    <h1 class="text-lg font-semibold text-green">
                        What is a Static Website?
                    </h1>
                </div>
                <div class="absolute top-3 right-3 text-black transition-transform duration-500 rotate-0 peer-checked:rotate-90">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 5l7 7-7 7" />
                      </svg>
                </div>
    
                <div class="overflow-hidden transition-all duration-500 max-h-0 peer-checked:max-h-full">
                    <div class="p-4">
                        <p>
                            A static website consists only of static webpages. A static web page (sometimes called a flat page or a stationary page) is a web page that is delivered to the user's web browser exactly as stored, in contrast to dynamic web pages which are generated by a web application.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
</template>